version: "3.8"

services:
  ai-content-extractor:
    build: .
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_CLOUD=true
    volumes:
      - .:/app
    restart: unless-stopped

  # Optional: Add Ollama service for local AI processing
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data:
